// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/module_include_list/module_include_list.go - DO NOT EDIT.

package include

import (
	// Import packages that need to register themselves.
	_ "github.com/aliksend/beats/filebeat/input/container"
	_ "github.com/aliksend/beats/filebeat/input/docker"
	_ "github.com/aliksend/beats/filebeat/input/kafka"
	_ "github.com/aliksend/beats/filebeat/input/log"
	_ "github.com/aliksend/beats/filebeat/input/redis"
	_ "github.com/aliksend/beats/filebeat/input/stdin"
	_ "github.com/aliksend/beats/filebeat/input/syslog"
	_ "github.com/aliksend/beats/filebeat/input/tcp"
	_ "github.com/aliksend/beats/filebeat/input/udp"
	_ "github.com/aliksend/beats/filebeat/module/apache"
	_ "github.com/aliksend/beats/filebeat/module/auditd"
	_ "github.com/aliksend/beats/filebeat/module/elasticsearch"
	_ "github.com/aliksend/beats/filebeat/module/haproxy"
	_ "github.com/aliksend/beats/filebeat/module/icinga"
	_ "github.com/aliksend/beats/filebeat/module/iis"
	_ "github.com/aliksend/beats/filebeat/module/kafka"
	_ "github.com/aliksend/beats/filebeat/module/kibana"
	_ "github.com/aliksend/beats/filebeat/module/logstash"
	_ "github.com/aliksend/beats/filebeat/module/mongodb"
	_ "github.com/aliksend/beats/filebeat/module/mysql"
	_ "github.com/aliksend/beats/filebeat/module/nats"
	_ "github.com/aliksend/beats/filebeat/module/nginx"
	_ "github.com/aliksend/beats/filebeat/module/osquery"
	_ "github.com/aliksend/beats/filebeat/module/postgresql"
	_ "github.com/aliksend/beats/filebeat/module/redis"
	_ "github.com/aliksend/beats/filebeat/module/santa"
	_ "github.com/aliksend/beats/filebeat/module/system"
	_ "github.com/aliksend/beats/filebeat/module/traefik"
)
